apiVersion: batch/v1
kind: Job
metadata:
  name: db-init
  namespace: wow
spec:
  template:
    spec:
      containers:
      - image: chz8494/wow-db-init:alpine
        env:
        - name: WOW_SERVER_NAME
          value: wow.k8s.tdlab.ca
        - name: MYSQL_ROOT_PASSWORD
          value: 123sqwert!
        - name: MYSQL_HOST
          value: db
        name: db-init
      restartPolicy: OnFailure
  backoffLimit: 4
