kind: ConfigMap
apiVersion: v1
metadata:
  name: http.nginx.wow
  namespace: kube-system
  labels:
    f5type: virtual-server
data:
  schema: "f5schemadb://bigip-virtual-server_v0.1.7.json"
  data: |
    {
      "virtualServer": {
        "backend": {
          "servicePort": 80,
          "serviceName": "default-nginx-controller-nginx-ingress-controller",
          "healthMonitors": [{
            "interval": 30,
            "protocol": "tcp",
            "timeout": 120
          }]
        },
        "frontend": {
          "virtualAddress": {
            "port": 8085,
            "bindAddr": "10.240.51.10"
          },
          "partition": "bare-k8s",
          "balance": "least-connections-node",
          "mode": "tcp"
        }
      }
    }
