apiVersion: v1
kind: List
items:
- apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    labels:
      app: wow
    name: wow-ingress
    namespace: wow
    annotations:
      virtual-server.f5.com/ip: "controller-default"
#      kubernetes.io/ingress.class: "f5"
  spec:
    rules:
    - host: wow.k8s.tdlab.ca
      http:
        paths:
        - backend:
            serviceName: wow-server
            servicePort: 8085
          path: /
    - host: wow-register.k8s.tdlab.ca
      http:
        paths:
        - backend:
            serviceName: wow-register
            servicePort: 80
          path: /
