apiVersion: v1
data:
  admin-email: Y2h6ODQ5NEBnbWFpbC5jb20=
  admin-email-password: TGFiQFdUSUMwME8=
kind: Secret
metadata:
  labels:
    wow: register
  name: register-admin
  namespace: wow
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    wow: register
  name: register
  namespace: wow
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      wow: register
  template:
    metadata:
      labels:
        wow: register
    spec:
      containers:
#      - image: lacsap/cmangos-web-register
      - image: chz8494/cmangos-register:latest
        name: cmangos-register
        env:
        - name: WOW_REGISTER_SERVER
          value: woworld.ga
        - name: WEB_PASSWORD
          value: WoW@tdlab.ca
        - name: MYSQL_HOST_CLASSIC
          value: db
        - name: MYSQL_DATABASE_CLASSIC
          value: classicrealmd
        - name: MYSQL_HOST_WOTLK
          value: db-wotlk
        - name: MYSQL_DATABASE_WOTLK
          value: wotlkrealmd
        - name: ADMIN_EMAIL
          valueFrom:
            secretKeyRef:
              key: admin-email-password
              name: register-admin
        - name: ADMIN_EMAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: admin-email
              name: register-admin
        ports:
        - containerPort: 80
 #       volumeMounts:
 #       - mountPath: /var/www/html
 #         name: register-claim0
 #         subPath: html
      restartPolicy: Always
 #     volumes:
 #     - name: register-claim0
 #       persistentVolumeClaim:
 #         claimName: register-claim0
