apiVersion: v1
kind: Service
metadata:
  labels:
    wow: register
  name: wow-register
  namespace: wow
spec:
  ports:
  - name: "http"
    port: 80
    targetPort: 80
  selector:
    wow: register
  type: ClusterIP
